### ISSUE TITLE
Grunt support

### ISSUE THREAD

**Issue by denismars** [vuejs/vue-component-compiler#10]
What's the plans on getting this configured as a grunt task? Not sure how one would re-code this to handle the conversations as a grunt task - love to get your help here.

**Comment by yyx990803** [comment]
This is just a generic compiler, but it assumes you are using some sort of
module packer that supports file transforms, e.g. Browserify or Webpack.
You can run these from grunt.

Or are you saying you want to use this without browserify/webpack?
