### ISSUE TITLE
less 不支持 @import

### ISSUE THREAD

**Issue by chaoren1641** [vuejs/vue-component-compiler#18]
如题，import外部文件时抛出异常
```
Error: './style/mixin.less' wasn't found. Tried - .
```

![image](https://cloud.githubusercontent.com/assets/404245/8470953/4a6ece1a-20c5-11e5-8987-4cda2cc1c24f.png)

**Comment by yyx990803** [comment]
目前在使用 vueify 的时候 import path 不是相对于文件，而是相对于你的构建工具运行目录的。建议改用 webpack + vue-loader，对于 import 的支持更好。

**Comment by chaoren1641** [comment]
OK，已经解决了。目前换webpack + vue-loader，感觉需要点成本。有空再研究，多谢 ：）

**Comment by miaotaizi** [comment]
@yyx990803 
你好, webpack + vue-loader 能import 其他package中的less 文件?
有相关的example不

**Comment by seekwe** [comment]
@yyx990803 打扰一下 这个问题好久了,到现在, rollup 下有什么解决方法吗
