### ISSUE TITLE
Ability to specify includePath for sass compiler

### ISSUE THREAD

**Issue by Morgul** [vuejs/vue-component-compiler#21]
I'm building a site that uses Bootstrap 4, and I compile Bootstrap's sass into my application. That works fine. However, if I'm writing a component that needs to import, say, the bootstrap `varaibles.scss` file, It doesn't work because the vue-component-compiler doesn't know about the import path.

What would be perfect would be a way to pass options to any of the compilers; this would give complete flexibility.

**Comment by yyx990803** [comment]
You can overwrite the default sass compile function with a custom one.

**Comment by Morgul** [comment]
Ok, for now, that works, but it'd be nice if support was added to pass options.
