### ISSUE TITLE
vueify-insert-css link error

### ISSUE THREAD

**Issue by domaniak** [vuejs/vue-component-compiler#24]
This line in index.js require relative path,

output += 'require("insert-css")(' + style + ');\n'

That cause a problem when we use vueify to make custom components. I always get the error:

gulp-notify: [Laravel Elixir] Browserify Failed!: Cannot find module 'insert-css' from '/Users/pathToMyLaravelProject/resources/assets/js/components'

'/resources/assets/js/components' is the folder where are my custom component.

**Comment by yyx990803** [comment]
That's requiring an npm module, not a relative link. You need to npm install `insert-css`.
