### ISSUE TITLE
Design / Roadmap

### ISSUE THREAD

**Issue by znck** [vuejs/vue-component-compiler#27]
`.vue` file compilation source is distributed and duplicated across various projects/repositories. There are inconsistencies (e.g. missing features etc.) among different variants. We are planning to build a bundler agnostic core.

A set of high level goals:
 - It should support all existing features (e.g. template languages, scoped styles, css modules, custom blocks etc.)
 - It should be usable in browser and node environment.

Any inputs @vuejs/collaborators @evan @eddyerburgh

**Comment by yyx990803** [comment]
oops, also created #28 - let's do it over there 😂
