### ISSUE TITLE
Should assemble require customBlocks?

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue-component-compiler#32]
I imagine there will be users who don't want to process custom blocks, but want to use vue-component-compiler. 

I don't think customBlocks should be a required argument for `assemble`

**Comment by znck** [comment]
I feel same. It shouldn't be a required argument.

**Comment by znck** [comment]
You can ignore custom blocks by passing an empty array. I believe current API (requiring custom blocks) does not limit users; we can keep it as it is.

**Comment by EddYerburgh** [comment]
If we can ignore by passing an empty array, I think we should also be able to leave it undefined.

**Comment by znck** [comment]
Custom blocks optional after #53
