### ISSUE TITLE
What happened to the hot reload API?

### ISSUE THREAD

**Issue by shawwn** [vuejs/vue-component-compiler#51]
Howdy,

How does hot reloading work with the latest code? (vue-component-compiler@3.0.0)

The last time I worked with this codebase was in December, and hot reloading was straightforward; simply pass in `isHot: true`:

https://github.com/vuejs/vue-component-compiler/blob/0ba6e8bc74e97d53e137f557d7e632c3686edef1/src/assemble.js#L102-L112

But that seems to have been removed. If you go to https://github.com/vuejs/vue-component-compiler/blob/master/src/assemble.js and search for "hot", there are no results.

What's the proper way to build vue components with hot reloading using the new API?

(If anyone is familiar with this, could you hop on our Slack at https://slack.parceljs.org/ and message me? I'm @shawwn on there.)

Thanks!

**Comment by znck** [comment]
We remove that as it was too coupled with webpack. We are rethinking the API to make it work with any bundler.

**Comment by znck** [comment]
Fixed in #53
