### ISSUE TITLE
Compatibility for more Async / await patterns

### ISSUE THREAD

**Issue by ch-luke** [vuejs/vue-component-compiler#55]
Would allow you to dynamically imports all your modules.

````js
<template>
  <div class="your html code"></div>  
</template>

<!-- Option 1 -->
<script>
(async () => {
  const { exportName } = await import('importName');

  export default {
    // component details
  };
})();
</script>

<!-- Option 2 -->
<script>
export default (async () => {
  const { exportName } = await import('importName');

  return {
    // component details
  };
})();
</script>
````

**Comment by znck** [comment]
What purpose does this API solve for you?

I may be missing something, but I feel you can still import modules asynchronously.

``` js

const something = import('something')

export default {
  async beforeCreate () {
     const { exportName } = await something

     this.exportName = exportName
  }
}

```

**Comment by ch-luke** [comment]
For me it helps with simplicity/readability. 

Your example, which I also use in my code, is a 2 step process. 1 - store promise import in a temp const and then 2 - when promise is ready update a reactive data value. 

Now image you have 10 imports per component  = 20 steps of code. IMHO that's a lot of unnecessary fluff.

**Comment by ch-luke** [comment]
Any news please?

**Comment by yyx990803** [comment]
This doesn't make sense. The exports from a vue file must be synchronous. I'm not convinced by the simplicity/readability argument either, on the contrary I think it makes things more complicated then it should.

**Comment by ch-luke** [comment]
Async / await is the future and makes things a lot less complicated and allows for dynamic loading. At the moment there are a lot of tedious complicated work arounds to support dynamic loading (e.g. like the one above in this comments chain). You can also for example add async to your methods, but this only works for @click events and not methods that are needed during rendering. It makes sense, but it up to you to take the good advice.

**Comment by ch-luke** [comment]
@yyx990803 - two questions for you? 

BTW, I really do like Vue and what you have created and really just have a different view on this one and only point.

1. How to migrate from actively importing everything  (e.g. using import { app } from "something") to lazy / just-in-time dynamic imports ? (to help with bundle size and loading speed)
2. Adopt an object oriented approach to programming exports ? E.g. move all requirements and imports into the export.

Can this be done with Vuejs?

**Comment by yyx990803** [comment]
I'm sorry but what @znck showed looks way cleaner and easier to understand to me than the examples you provided. Components are values, not modules. Async happens inside a component's lifecycle hooks, not where it is defined.

**Comment by chrisnicola** [comment]
@ch-luke if you want to handle dynamic imports why not load them as @yyx990803 is suggesting, in the lifecycle hooks.

Is that not the purpose of dynamic imports with something like webpack? Do do code splitting and lazy load code as needed?

**Comment by ch-luke** [comment]
@chrisnicola/ @znck  / @yyx990803 , have you tried the above code snippet in a project before? 

It actually doesn't work. Dealing with promises await, by design, does not pause execution so the parser will continue with the rest of the functions / lifecycle stages etc and might get to the point where you used the **this.exportName** before it has been resolved. Hence it is important to give initial values like in the updated example below:

```js
export default {
  async beforeCreate () {
     this.exportName = () => undefined
     const { exportName } = await import('something')

     this.exportName = exportName
  }
}
```

But this example still doesn't always work like I am finding out when using it in modals (components methods are firing quicker than the imports can be resolved). Currently, I am having to define the imports in the parent and then calling them from the child component **this.$parent.exportName** - not really ideal. 

How can we constructively take this forward ?

**Comment by chrisnicola** [comment]
I understand how promises work. I may not fully understand what you are trying to achieve though.

So to clarify, are you suggesting that VueJS have a way to have a lifecycle hook `await` something before rendering. In order words, if `beforeCreate` is async (i.e., returns a promise) it should detect the promise and await it before continuing with the render cycle.

@yyx990803 that's an interesting idea and a problem that I have run into, though I'll admit it isn't particularly hard to work around, but just having some component `loading` state associated with the promise or other solution depending on the context.

I wonder if lifecycle hooks that worked similar to router guards (https://router.vuejs.org/en/advanced/navigation-guards.html) would be useful?

```
export default {
  // lifecycle hook that expects a promise

  async awaitCreate() {
     this.exportName = () => undefined
     const { exportName } = await import('something')
     this.exportName = exportName
  }

  // or alternatively passes an explicit continue function argument

  async awaitCreate(continue) {
     this.exportName = () => undefined
     const { exportName } = await import('something')
     this.exportName = exportName
     continue() 
  }
}

```

**Comment by yyx990803** [comment]
@ch-luke the snippet assumes you have `exportsName` declared as a **reactive** property in `data`. That's common practice if you want to trigger updates by setting a value async.

**Comment by ch-luke** [comment]
@yyx990803, thanks for your response. Yes took that into account, but the snippet really does not work.

I do see something here. As you mentioned , components are synchronise and introducing async to any part of it will alter the load sequence . You are suggesting using reactivity as a solution, but by design that is a post-fix band aid approach and believe there is a better way. 

So I am suggesting we use async/await to keep components synchronise and ensure the load order of the lifecycle stages . E.g. 

```js

// About to load the component
if (hasAsync(comp)) {
  // Load stages in order
  await loadMethods()
  await loadBeforeCreated()
  await loadCreated()

  ...

  // Shouldn't we also introduce a asyncMethods tag for non load critical
  // code such as button clicks. This will be lazy loaded and not waited for
  loadAsyncMethods()
} else {
  // Load component normally
}

```

**Comment by afwn90cj93201nixr2e1re** [comment]
Is there anyway to make it?
