### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by davidnagli** [vuejs/vue-component-compiler#57]
Hi :)

I was just wondering about the status of this project, and when the next release is planned for. I noticed that there haven't been any changes for almost two months. 

Are there any plans to resume work on this project? Are there any plans to push the current changes to the npm package?

parcel-bundler/parcel#1052

**Comment by yyx990803** [comment]
The current WIP branch is doing a bit too much and we are moving lower-level implementations into https://github.com/vuejs/component-compiler-utils - this package will likely be refactored to provide a simpler, higher-level API instead.
