### ISSUE TITLE
[Question] Is there a rough timeline for the rewrite?

### ISSUE THREAD

**Issue by shreeve** [vuejs/vue-component-compiler#58]
With all the goodness going into Vue right now, I assume the rewrite of `vue-component-compiler` isn't at the top of the list. Having said that, is there a _rough_ idea for when the rewrite is intended to be complete?

**Comment by yyx990803** [comment]
FYI a large chunk of the work will be done in https://github.com/vuejs/component-compiler-utils instead. See https://github.com/vuejs/component-compiler-utils/issues/1 for the work left. It will most likely be done within the next month.
