### ISSUE TITLE
Please update the version of dependence `@vue/component-compiler-utils` to `^2.0.0`

### ISSUE THREAD

**Issue by JunreyCen** [vuejs/vue-component-compiler#76]
I need something update in dependence `@vue/component-compiler-utils` with version 2.0.0 above.

**Comment by hiendv** [comment]
I'm having problems with async postcss plugins: `Use process(css).then(cb) to work with async plugins`
It's fixed in https://github.com/vuejs/component-compiler-utils/commit/54464d61774ae0481b249d358c3b8fcb3c63ad12
