### ISSUE TITLE
ES6 injection

### ISSUE THREAD

**Issue by cristovao-trevisan** [vuejs/vue-component-compiler#79]
Hello,
I am using rollup-plugin-vue, but it breaks uglify as of now.
The reason is the es6 syntax of the injected (like `*const* __vue_inject_styles__`) by this project.

Any thoughts on this??

**Comment by tralves** [comment]
Hi! I can't remember exactly how, but rollup should be using babel...

In any case, please update to the latest template. It is the only one currently supported and in active development.
The easiest update path is to create a new app and copy your code to the new project.

See: https://nativescript-vue.org/en/docs/getting-started/quick-start/
https://nativescript-vue.org/en/docs/getting-started/upgrade-guide/

**Comment by huochunpeng** [comment]
I would say this is neither a vue bug nor rollup bug.

Switch from uglify to terser (uglify-es successor).
https://github.com/TrySound/rollup-plugin-terser

**Comment by cristovao-trevisan** [comment]
I've found tenser some time ago, but forgot about this issue. Sorry, closing it now
